### PR TITLE
for: add test cases and comments

### PR DESCRIPTION
**Pull request by Henry-Gao-2004**
Partially For kubebb/core#194

Added test cases for Repository.NamespacedName()

Also added comments and corrected typos

### CODE REVIEW

**Comment by Abirdcfly** [comment]
> Partially fix #194

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword `fix` keyword will **close** this issue, but we're not done with it, we don't want to close it, as the kubernetes guys did, we can use the `for` keyword.

**Review by bjwswang — CHANGES_REQUESTED** [review]
Good job! 👍   pls merge these changes into one commit 😄  @Henry-Gao-2004

**Comment by bjwswang** [comment]
> 

Good point! We can add this to our contribute guidelines https://kubebb.github.io/website/docs/contribute#pr%E8%A7%84%E8%8C%83

**Comment by bjwswang** [comment]
> > Partially fix #194
> 
> https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword `fix` keyword will **close** this issue, but we're not done with it, we don't want to close it, as the kubernetes guys did, we can use the `for` keyword.(or any other keyword, we just want link to this issue.)

Good point! We can add this to our contribute guidelines https://kubebb.github.io/website/docs/contribute#pr%E8%A7%84%E8%8C%83

**Comment by Henry-Gao-2004** [comment]
I think I got something wrong 😭

I will create a new branch and copy the changes there!

**Comment by Henry-Gao-2004** [comment]
All commits are merged into one now!

**Comment by Abirdcfly** [comment]
Very good, now it is in one commit, now we need to modify a little bit, change the commit message of this commit, "All in One!" It doesn't say what it did, you can refer to the unfinished https://gist.github.com/Abirdcfly/b942d4e9d44f3fb71344b92b979c8d40 to write an appropriate commit message. 

The reference command may be
```bash
$ git commit --amend
$ in vim, change commit message....
$ git push origin documentation --force
```

**Comment by Henry-Gao-2004** [comment]
Thank you very much! The commit message is now: "[chore: add test cases for Repository.NamespacedName](https://github.com/kubebb/core/pull/197/commits/0af4831d54903d8551004c4273cb4ba9b273a2de)".

**Review by Abirdcfly — APPROVED** [review]

**Review by bjwswang — APPROVED** [review]

**Comment by bjwswang** [comment]
@Henry-Gao-2004 Thanks for your work! Can you add more test cases for other functions in this `repository.go`?

**Comment by Henry-Gao-2004** [comment]
Sure no problem at all!

**Pull request merged**
