### PR TITLE
chore: add test cases for componentplan.go

### PR DESCRIPTION
**Pull request by Henry-Gao-2004**
#### Which issue(s) this PR fixes

For #194

### CODE REVIEW

**Comment by Henry-Gao-2004** [comment]
It seems like any function involving a condition with LastTransitionTime cannot be tested, as it is impossible to generate an expected condition (because LastTransitionTime uses metav1.Now()). Can I know if there is a way to test those methods, or should we just leave them untested?

**Comment by 0xff-dev** [comment]
> It seems like any function involving a condition with LastTransitionTime cannot be tested, as it is impossible to generate an expected condition (because LastTransitionTime uses metav1.Now()). Can I know if there is a way to test those methods, or should we just leave them untested?

I think you can ignore the comparison of the `LastTransitionTime` field.
This test function has the same problem as you. I am also ignoring the comparison of the time field.

https://github.com/kubebb/core/blob/2b6df16e695115c6820db52120bdeffe265187cd/api/v1alpha1/subscription_test.go#L38

**Comment by Henry-Gao-2004** [comment]
> I think you can ignore the comparison of the `LastTransitionTime` field. This test function has the same problem as you. I am also ignoring the comparison of the time field.
> 
> https://github.com/kubebb/core/blob/2b6df16e695115c6820db52120bdeffe265187cd/api/v1alpha1/subscription_test.go#L38

Great idea! I will write the test cases for all functions and then be ready for review again! Thank you very much for your suggestion!

**Review by Abirdcfly — APPROVED** [review]
👍 👍👍 👍👍👍

**Review by bjwswang — CHANGES_REQUESTED** [review]
resolve the confilicts

**Comment by Henry-Gao-2004** [comment]
The branch is now up to date!

**Review by bjwswang — APPROVED** [review]

**Pull request merged**
