### PR TITLE
feat: oci basic support - inspect a chart using the url

### PR DESCRIPTION
**Pull request by Henry-Gao-2004**
To get the properties of a chart, I found two possible methods online: 

Skopeo: Skopeo uses a lot of self-defined methods and it outputs the result to the console. There is no way to access the data in the method, unless we copy all the code and then do some edits. 

Helm: Helm pull can be a possible approach. The problem is that it seems "helm pull" downloads the file to a unknown place and we need to use LocateChart (which should not be used because this function writes logs to stdout. The approach in our program uses download chart, which requires a repository, but for now all oci images we have do not have a repository. 

Any suggestion or help would be appreciated! 

Signed-off-by: Henry-Gao-2004 henrygao04@gmail.com

### CODE REVIEW

**Comment by Henry-Gao-2004** [comment]
The problem is on line 149 of pkg/repository/chartmuseum.go. For now I am using Loader.load, which does not work because it requires a chart path instead of url.

**Comment by Abirdcfly** [comment]
> copy all the code and then do some edits.

This approach is not very recommended

> "helm pull" downloads the file to a unknown place

Maybe We can specify the `--untar` and `destination` parameter, which can be in a temporary folder or a folder defined by `reponame-reponamespace`, since we just want to get and prase the `Chart.yaml` file in it.

> and we need to use LocateChart (which should not be used because this function writes logs to stdout. 

A similar situation was encountered before, hence we have the [`HelmWrapper.prepare` function](https://github.com/kubebb/core/blob/e4c0ba5827c0485b6757b28f9ec963413c6421e3/pkg/helm/helm.go#L265), feel free to modify or copy your own function.

**Comment by Henry-Gao-2004** [comment]
> Maybe We can specify the `--untar` and `destination` parameter, which can be in a temporary folder or a folder defined by `reponame-reponamespace`, since we just want to get and prase the `Chart.yaml` file in it.
Thank you! I wrote a pull function in helm and used the existing ChartDownload function. It seemed like it should work fine, but now an oci repository is needed for the ChartDownload function to work. I will also check how the original helm pull function works! 

> A similar situation was encountered before, hence we have the [HelmWrapper.prepare function](https://github.com/kubebb/core/blob/e4c0ba5827c0485b6757b28f9ec963413c6421e3/pkg/helm/helm.go#L265), feel free to modify or copy your own function.
The prepare function is quite useful! I copied its structure to the helm function to load the chart. 

Thank you very much for the great suggestions!

**Comment by Henry-Gao-2004** [comment]
Based on this doc, it seems like helm does not support "repo add" for oci repositories yet: 
https://helm.sh/zh/docs/topics/registries/

I will try to write a new pull function that will pull the chart without accessing the repository!

**Comment by Abirdcfly** [comment]
> helm does not support "repo add" for oci repositories yet
Yes

在构建component部分，我认为这里有2个部分需要处理：
1. 知道oci地址的情况下，获取全部的版本（这里应该是需要参考oras的地方？）
2. 通过精确的版本信息获取chart.yaml并解析（这里应该可以直接调用helm pull，因为helm pull支持）
然后将全部结果填充到component中

至于安装部分，helm install 或者upgrade本身就支持oci格式。只需要适配一些参数即可。

In the build component part, I think there are 2 parts that need to be dealt with here:
1. get the full version if we know the oci address (this should be the place to refer to oras?) （for example: give us `oci://registry-1.docker.io/abirdcfly/nginx` we should find `15.1.0`)
2. get the `Chart.yaml` with the exact version information and parse it (here we can call `helm pull` command directly, because helm pull supports `helm pull oci://registry-1.docker.io/abirdcfly/nginx --version 15.1.0`)
And then populate the `component` with all the results. 

As for the installation part, `helm install/upgrade` itself supports the oci format(`helm install <my-release> oci://registry-1.docker.io/abirdcfly/nginx --version 15.1.0`). we just need to adapt some parameters.

**Comment by Henry-Gao-2004** [comment]
> 1. get the full version if we know the oci address

Yes, this part has been completed! I was inspired by "helm show" and it should work after I got the chart. 

> 2. get the `Chart.yaml` with the exact version information and parse it

Based on my understanding, I can get the component without the version information because there is only one component related to the link (helm install <my-release> oci://registry-1.docker.io/abirdcfly/nginx). In the future when helm supports adding oci-repos, probably this will be needed. 

> As for the installation part, `helm install/upgrade` itself supports the oci format(`helm install <my-release> oci://registry-1.docker.io/abirdcfly/nginx --version 15.1.0`). we just need to adapt some parameters.

Great idea! I will look into helm install/upgrade to see how to get charts in oci format. Thank you very much!

**Comment by Abirdcfly** [comment]
> I can get the component without the version information

In this case, the component corresponding to the latest version is fetched.

Consider the following example, as you can see from the https://github.com/JimCronqvist/helm-charts/pkgs/container/helm-charts%2Fargocd-plugin-generator , there are actually two versions, `0.1.0` and `0.1.1`, and when no version is specified, the latest version is fetched.

```bash
# helm pull --untar oci://ghcr.io/jimcronqvist/helm-charts/argocd-plugin-generator
Pulled: ghcr.io/jimcronqvist/helm-charts/argocd-plugin-generator:0.1.1
Digest: sha256:53c87751a3885285975a9ce59d56a0efb21d46c2df27ed5e6a411ae14b700a95
```

**Comment by Henry-Gao-2004** [comment]
Thank you very much for the explanation! For now it seems like there is only one version in the registry, but I will allow the user to specify the version in the yaml file later!

**Pull request closed without merging**
